on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install and set up Java
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install java 17.0.10-zulu
          sdk default java 17.0.10-zulu

      - name: Install Flutter
        run: |
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.7.12-stable.tar.xz
          tar xf flutter_linux_3.7.12-stable.tar.xz -C $HOME
          echo "$HOME/flutter/bin" >> $GITHUB_PATH

      - name: Check Flutter Version and Doctor Output
        run: |
          flutter --version
          flutter doctor
          flutter pub get

      - name: Build Release
        run: flutter build appbundle --release

      - name: Archive Release
        uses: actions/upload-artifact@v3
        with:
          name: aab
          path: build/app/outputs/bundle/release/*.aab

      - name: Update APK on VM using sshpass
        env:
          VM_PASSWORD: ${{ secrets.VM_PASSWORD }}
        run: |
          sudo apt-get install -y sshpass
          sshpass -p $VM_PASSWORD scp -o StrictHostKeyChecking=no ./build/app/outputs/flutter-apk/app-release.aab faizanali@20.10.195.124:/tmp/app-release.aab
          sshpass -p $VM_PASSWORD ssh -o StrictHostKeyChecking=no faizanali@20.10.195.124 "sudo rm -f /var/www/app-release.aab && sudo mv /tmp/app-release.aab /var/www/"
